import { Roboto_Mono } from "next/font/google";

const robotoMono = Roboto_Mono({
    variable: "--font-roboto-mono",
    subsets: ["latin-ext"],
});

export const metadata = {
    title: "Landing Page",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${robotoMono.variable}`}>{children}</body>
        </html>
    );
}
